# Generated by Django 3.0.6 on 2020-06-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articles_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, height_field=220, upload_to='img', width_field=450),
        ),
    ]
